services:
  datalake:
    image: postgres:15-alpine
    container_name: elections_2022_datalake
    restart: unless-stopped
    ports:
        - 6000:5432
    volumes:
        - /usr/docker/postgresql/elections_2022:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres