services:
  datalake:
    image: postgres:15-alpine
    container_name: elections_2022_datalake
    restart: unless-stopped
    ports:
        - 6000:5432
    volumes:
        - ./postgres_dw:/var/lib/postgresql/data
        - ./pg/postgres/seeds:/docker-entrypoint-initdb.d
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres