apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: airflow-postgresql
spec:
  serviceName: 'postgresql'
  replicas: 1
  selector:
    matchLabels:
      app: airflow-postgresql
  template:
    metadata:
      labels:
        app: airflow-postgresql
    spec:
      containers:
        - name: postgresql
          image: postgres:13
          env:
            - name: POSTGRES_USER
              value: "airflow_user"
            - name: POSTGRES_PASSWORD
              value: "airflow_password"
            - name: POSTGRES_DB
              value: "airflow"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: airflow-postgresql-pvc
              mountPath: /var/lib/postgresql-airflow/data
      volumes:
        - metadata:
          name: postgresql-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
        # - name: airflow-postgresql-pvc
        #   persistentVolumeClaim:
        #     claimName: airflow-postgresql-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-postgresql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi